apiVersion: v1
kind: Service
metadata:
  name: guestbook-lb
  namespace: guestbook
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: guestbook-ui
